### ISSUE TITLE
Ruby capstone project

### ISSUE THREAD

**Issue by edi-sipka** [edi-sipka/Catalog_of_Things#26]
Our Github project link is: https://github.com/edi-sipka/Catalog_of_Things 

Our team has 3 members. It's me (@edi-sipka), Aamir Khan (@aamirkhan2478), and Betsegaw Sebside(@betses)

- Team member#1 is Edi Šipka(@edi-sipka )
-  Team member#2 is Aamir Khan(@aamirkhan2478 )
-  Team member#3 is  Betsegaw Sebside(@betses )

**Comment by youmari** [comment]
# Project Approved :trophy: :tada: 🟢 

Hi @edi-sipka @aamirkhan2478 @betses 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 


:heavy_check_mark: Details PR title and description.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
